version: "3.5"
services:
  redis_db:
    container_name: minivalist-redis
    image: redis
    ports:
      - "6379"
    networks:
      - nginx-network
  db:
    container_name: minivalist-db
    image: "postgres:11"
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - nginx-network
  etl:
    container_name: minivalist-etl
    image: cinnapple/minivalist-etl
    volumes:
      - .env:/usr/app/.env
    command: yarn run prod-all
    restart: always
    depends_on:
      - db
    networks:
      - nginx-network
  api:
    container_name: minivalist-api
    image: cinnapple/minivalist-api
    ports:
      - "4000:4000"
    volumes:
      - .env:/usr/app/.env
    command: node index.js
    restart: always
    depends_on:
      - db
    links:
      - redis_db
    networks:
      - nginx-network
  web:
    container_name: minivalist-web
    image: cinnapple/minivalist-web
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - api
    networks:
      - nginx-network

volumes:
  database:
    external: true

networks:
  nginx-network:
    name: nginx-network
