version: '3.5'

services:

  api:
    container_name: api
    image: cinnapple/mini-validator-list-api
    networks:
      - nginx-network
    volumes:
      - .env:/usr/api/.env
      - ./secret:/usr/api/secret
    restart: always
    environment:
      NODE_ENV: production

  mini-validator-list-frontend:
    container_name: mini-validator-list-frontend
    image: cinnapple/mini-validator-list-frontend
    networks:
      - nginx-network
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production

networks:
  nginx-network:
    name: nginx-network
